name: el3ctron
description: "Latinoamericano, cardionauta, ingeniero de sistemas, amante del arte, el hacking y las cosas hechas con cari√±o e inteligencia."
markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
excerpt_separator: <!-- more -->
exclude: [rtd.sublime-project, rtd.sublime-workspace, CNAME, Gruntfile.js, package.json, README.md]
abs_url: http://twitter.com/el3ctron
